# Generated by Django 5.2.7 on 2025-11-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book records'), ('can_create', 'Can create book records'), ('can_edit', 'Can edit book records'), ('can_delete', 'Can delete book records')]},
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
